apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-service-demo-app-deployment
  labels:
    app: k8s-service-demo-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-service-demo-app-pods
  template:
    metadata:
      labels:
        app: k8s-service-demo-app-pods
    spec:
      containers:
      - name: k8s-service-demo-app
        image: sambhavanisantosh322/k8s-service-demo-app
        ports:
        - containerPort: 3000

