apiVersion: v1
kind: Service
metadata:
  name: k8s-service-demo-app-service
spec:
  selector:
    app: k8s-service-demo-app-pods
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007
  type: NodePort
